/* eslint-disable */
/**
 * Photo manifest — generated by /tmp/cc-pull/finalize.mjs from
 * curated CompanyCam pulls (May 2026). Pre-resized to max 1600px
 * longest edge, EXIF stripped, mozjpeg q=78.
 *
 * Regenerate by re-running the puller + finalizer in /tmp/cc-pull/.
 * The 'role' field hints where a photo is intended to appear, but
 * the manifest helpers below let any page pick the most relevant.
 */

export interface SitePhoto {
  src: string;
  alt: string;
  category: string;
  area: string;
  service: string;
  role: string;
  width: number;
  height: number;
  bytes: number;
}

export const PHOTOS: SitePhoto[] = [
  {
    "src": "/photos/hero-1.jpg",
    "alt": "Backyard landscape design with manicured lawn, palms, and screened pool — Firsthand Lawn and Landscape",
    "category": "hero",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "hero",
    "width": 1600,
    "height": 1200,
    "bytes": 401336
  },
  {
    "src": "/photos/hardscape-1.jpg",
    "alt": "Travertine pool deck with raised spa and waterfall feature in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "service-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 287883
  },
  {
    "src": "/photos/hardscape-2.jpg",
    "alt": "Paver driveway installation in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 366935
  },
  {
    "src": "/photos/hardscape-3.jpg",
    "alt": "Paver patio adjacent to screened pool enclosure in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "windermere",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 427773
  },
  {
    "src": "/photos/hardscape-4.jpg",
    "alt": "Brick paver driveway in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 295159
  },
  {
    "src": "/photos/hardscape-5.jpg",
    "alt": "Two-story Mediterranean home with paver driveway and lawn in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "orlando",
    "service": "hardscape-installation",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 285920
  },
  {
    "src": "/photos/sod-1.jpg",
    "alt": "Fresh St. Augustine sod installation on a Central Florida front lawn — Firsthand Lawn and Landscape",
    "category": "sod",
    "area": "orlando",
    "service": "sod-installation",
    "role": "service-hero",
    "width": 1024,
    "height": 768,
    "bytes": 178796
  },
  {
    "src": "/photos/sod-2.jpg",
    "alt": "Side-yard sod with mature oak canopy in Central Florida — Firsthand Lawn and Landscape",
    "category": "sod",
    "area": "orlando",
    "service": "sod-installation",
    "role": "area-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 343952
  },
  {
    "src": "/photos/lawn-1.jpg",
    "alt": "Maintained lawn with mowing stripes under mature oak canopy in Central Florida — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "service-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 419293
  },
  {
    "src": "/photos/lawn-2.jpg",
    "alt": "Weekly lawn maintenance on a Central Florida residential property — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 440788
  },
  {
    "src": "/photos/lawn-3.jpg",
    "alt": "Mowed lawn alongside hedge and pool enclosure in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "windermere",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 436315
  },
  {
    "src": "/photos/lawn-4.jpg",
    "alt": "Side-yard lawn alongside hedge in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "bay-hill",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 366884
  },
  {
    "src": "/photos/landscape-1.jpg",
    "alt": "Landscape design with mixed beds alongside a luxury home in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "service-hero",
    "width": 1200,
    "height": 1600,
    "bytes": 462064
  },
  {
    "src": "/photos/landscape-2.jpg",
    "alt": "Lush backyard with palm and hedge screening in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "orlando",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 389296
  },
  {
    "src": "/photos/landscape-3.jpg",
    "alt": "Tall Podocarpus hedge along a Bay Hill property line — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "bay-hill",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 387295
  },
  {
    "src": "/photos/landscape-4.jpg",
    "alt": "Mixed planting bed with palms and ground covers in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 240,
    "height": 320,
    "bytes": 17230
  },
  {
    "src": "/photos/stump-1.jpg",
    "alt": "Palm cluster base in Bay Hill, FL — typical stump-grinding candidate. Firsthand Lawn and Landscape",
    "category": "stump",
    "area": "bay-hill",
    "service": "stump-grinding-removal",
    "role": "service-hero",
    "width": 1200,
    "height": 1600,
    "bytes": 384178
  },
  {
    "src": "/photos/bamboo-1.jpg",
    "alt": "Before-and-after of bamboo removal and yard transformation by Firsthand Lawn and Landscape",
    "category": "bamboo",
    "area": "bay-hill",
    "service": "bamboo-trimming-removal",
    "role": "service-hero",
    "width": 1440,
    "height": 1440,
    "bytes": 383532
  },
  {
    "src": "/photos/winter-park-1.jpg",
    "alt": "Oak-shaded front yard at a Spanish-style home near Lake Ivanhoe in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "winter-park",
    "area": "winter-park",
    "service": "lawn-maintenance",
    "role": "area-hero",
    "width": 1200,
    "height": 1600,
    "bytes": 449742
  },
  {
    "src": "/photos/winter-park-2.jpg",
    "alt": "Modern white-stucco home with palms in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "winter-park",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "area-secondary",
    "width": 180,
    "height": 240,
    "bytes": 12131
  },
  {
    "src": "/photos/windermere-1.jpg",
    "alt": "Wide paver driveway at a Mediterranean estate in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "windermere",
    "area": "windermere",
    "service": "hardscape-installation",
    "role": "area-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 384979
  },
  {
    "src": "/photos/windermere-2.jpg",
    "alt": "Single-story estate home and landscape in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "windermere",
    "area": "windermere",
    "service": "landscape-design",
    "role": "area-secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 314615
  },
  {
    "src": "/photos/bay-hill-1.jpg",
    "alt": "Estate home with mature magnolia and lawn in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "bay-hill",
    "area": "bay-hill",
    "service": "lawn-maintenance",
    "role": "area-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 498917
  },
  {
    "src": "/photos/commercial-1.jpg",
    "alt": "Commercial property landscape maintenance in Central Florida — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1200,
    "height": 1600,
    "bytes": 441253
  },
  {
    "src": "/photos/commercial-2.jpg",
    "alt": "Commercial office landscape with paver entrance in Central Florida — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 280456
  },
  {
    "src": "/photos/portfolio-1.jpg",
    "alt": "Mediterranean home with palm-lined drive in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "orlando",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 361396
  },
  {
    "src": "/photos/portfolio-2.jpg",
    "alt": "Backyard with paver patio and fresh sod in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "orlando",
    "service": "hardscape-installation",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 394749
  },
  {
    "src": "/photos/portfolio-3.jpg",
    "alt": "Tile-roof home with mature hedge bed in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 354103
  },
  {
    "src": "/photos/portfolio-4.jpg",
    "alt": "Wraparound porch with magnolia and trimmed hedges in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 439226
  },
  {
    "src": "/photos/portfolio-5.jpg",
    "alt": "Single-story Florida home with metal roof and large front lawn in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 237797
  },
  {
    "src": "/photos/commercial-3.jpg",
    "alt": "Commercial dental practice frontage with new gravel bed and landscaping in Orlando, FL — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "orlando",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1200,
    "height": 1600,
    "bytes": 455986
  },
  {
    "src": "/photos/landscape-5.jpg",
    "alt": "Fresh mulch and plant install along a Central Florida residential side yard — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 364872
  }
];

export function photosByService(slug: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.service === slug);
}

export function photosByArea(slug: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.area === slug);
}

export function photosByRole(role: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.role === role);
}

export function findPhoto(predicate: (p: SitePhoto) => boolean): SitePhoto | undefined {
  return PHOTOS.find(predicate);
}

/** Pick one photo with role exactly matching, fall back to any of category. */
export function pickHero(role: string, category: string): SitePhoto | undefined {
  return PHOTOS.find((p) => p.role === role) ?? PHOTOS.find((p) => p.category === category);
}
