/* eslint-disable */
/**
 * Photo manifest — generated by /tmp/cc-pull/finalize.mjs from
 * curated CompanyCam pulls (May 2026). Pre-resized to max 1600px
 * longest edge, EXIF stripped, mozjpeg q=78.
 *
 * Regenerate by re-running the puller + finalizer in /tmp/cc-pull/.
 * The 'role' field hints where a photo is intended to appear, but
 * the manifest helpers below let any page pick the most relevant.
 */

export interface SitePhoto {
  src: string;
  alt: string;
  category: string;
  area: string;
  service: string;
  role: string;
  width: number;
  height: number;
  bytes: number;
  /**
   * True when the photo is an AI-generated illustration rather than a
   * real Firsthand project shot. Surfaces a visible "Illustrative
   * example — actual results vary" caption beneath the photo. Honesty
   * requirement (not a style preference); also reinforced by the
   * "— illustrative" suffix on the alt text.
   */
  illustrative?: boolean;
}

export const PHOTOS: SitePhoto[] = [
  // ── Ryan-curated batch (2026-05-24) ──────────────────────────────────
  // Hand-picked by Ryan from his own project archive in response to v1
  // site review. Placed at the TOP of the array so pickHero() finds
  // them first for hero / service-hero roles. The "-ryan-" infix in
  // filenames flags personally-curated assets.
  {
    "src": "/photos/sod-installation-ryan-1.jpg",
    "alt": "Before-and-after of complete sod installation at Central Florida residence — bare yard transformed into full green lawn with irrigation — Firsthand Lawn and Landscape",
    "category": "sod",
    "area": "central-florida",
    "service": "sod-installation",
    "role": "service-hero",
    "width": 1440,
    "height": 1440,
    "bytes": 594211
  },
  // ── AI illustrations (DALL-E 3, 2026-05-25) ─────────────────────────
  // The four services Ryan didn't have real CompanyCam coverage for.
  // illustrative=true triggers a visible caption beneath the photo on
  // every render, and the alt text ends in "— illustrative" per the
  // honesty requirement.
  {
    "src": "/photos/irrigation-illustration.jpg",
    "alt": "Residential irrigation system spraying water across a Central Florida front lawn — illustrative",
    "category": "irrigation",
    "area": "central-florida",
    "service": "irrigation",
    "role": "service-hero",
    "width": 1600,
    "height": 900,
    "bytes": 442542,
    "illustrative": true
  },
  {
    "src": "/photos/tree-trimming-illustration.jpg",
    "alt": "Freshly trimmed mature oak canopy in a Central Florida residential yard — illustrative",
    "category": "tree",
    "area": "central-florida",
    "service": "tree-trimming-removal",
    "role": "service-hero",
    "width": 1600,
    "height": 900,
    "bytes": 557840,
    "illustrative": true
  },
  {
    "src": "/photos/stump-grinding-illustration.jpg",
    "alt": "Freshly ground stump with clean wood-chip fill in a Central Florida lawn — illustrative",
    "category": "stump",
    "area": "central-florida",
    "service": "stump-grinding-removal",
    "role": "service-hero",
    "width": 1600,
    "height": 900,
    "bytes": 475932,
    "illustrative": true
  },
  {
    "src": "/photos/bamboo-real-1.jpg",
    "alt": "Bamboo privacy screen at a Central Florida residential property — Firsthand Lawn and Landscape",
    "category": "bamboo",
    "area": "central-florida",
    "service": "bamboo-trimming-removal",
    "role": "service-hero",
    "width": 1280,
    "height": 960,
    "bytes": 546304
  },
  {
    "src": "/photos/lawn-maintenance-secondary-ryan-1.jpg",
    "alt": "Manicured strip lawn with charcoal paver driveway, modern stucco home, and podocarpus hedge — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "service-hero",
    "width": 1280,
    "height": 960,
    "bytes": 540631
  },
  {
    "src": "/photos/portfolio-ryan-replacement-1.jpg",
    "alt": "Manicured podocarpus hedges flanking a curving residential sidewalk in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "portfolio-card",
    "width": 1080,
    "height": 1920,
    "bytes": 725148
  },
  {
    "src": "/photos/college-park-area-hero.jpg",
    "alt": "Professionally maintained landscaping in College Park, FL",
    "category": "lawn",
    "area": "college-park",
    "service": "lawn-maintenance",
    "role": "area-hero",
    "width": 1920,
    "height": 1080,
    "bytes": 467648
  },
  {
    "src": "/photos/bamboo-illustration.jpg",
    "alt": "Maintained bamboo privacy screen in a Central Florida backyard — illustrative",
    "category": "bamboo",
    "area": "central-florida",
    "service": "bamboo-trimming-removal",
    "role": "secondary",
    "width": 1600,
    "height": 900,
    "bytes": 688053,
    "illustrative": true
  },
  {
    "src": "/photos/property-cleanup-hero.jpg",
    "alt": "Before-and-after of overgrown Central Florida property cleanup — stucco home with brick driveway transformed from neglected to manicured — Firsthand Lawn and Landscape",
    "category": "property-cleanup",
    "area": "central-florida",
    "service": "property-cleanup",
    "role": "service-hero",
    "width": 1440,
    "height": 1440,
    "bytes": 590218
  },
  {
    "src": "/photos/portfolio-before-after-1.jpg",
    "alt": "Before-and-after of property cleanup at a Mediterranean estate in Central Florida — overgrown landscape around brick paver driveway restored to manicured beds and lawn — Firsthand Lawn and Landscape",
    "category": "before-after",
    "area": "central-florida",
    "service": "property-cleanup",
    "role": "portfolio-card",
    "width": 1200,
    "height": 1200,
    "bytes": 618614
  },
  {
    "src": "/photos/portfolio-before-after-2.jpg",
    "alt": "Before-and-after of sod installation under mature oak in Central Florida — patchy thinning lawn replaced with lush green turf — Firsthand Lawn and Landscape",
    "category": "before-after",
    "area": "central-florida",
    "service": "sod-installation",
    "role": "portfolio-card",
    "width": 1200,
    "height": 1200,
    "bytes": 749683
  },
  {
    "src": "/photos/portfolio-before-after-4.jpg",
    "alt": "Before-and-after of side-yard restoration in Central Florida — dirt and leaf cover under oak transformed to manicured grass — Firsthand Lawn and Landscape",
    "category": "before-after",
    "area": "central-florida",
    "service": "property-cleanup",
    "role": "portfolio-card",
    "width": 1200,
    "height": 1200,
    "bytes": 780288
  },
  {
    "src": "/photos/hero-ryan-1.jpg",
    "alt": "Two-story Mediterranean home with travertine walkway, palms, and bougainvillea in Central Florida — Firsthand Lawn and Landscape",
    "category": "hero",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "hero",
    "width": 1280,
    "height": 720,
    "bytes": 397300
  },
  {
    "src": "/photos/landscape-ryan-1.jpg",
    "alt": "Mature landscape design with palms, oak canopy, and stucco home in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "service-hero",
    "width": 1280,
    "height": 720,
    "bytes": 527630
  },
  {
    "src": "/photos/landscape-ryan-2.jpg",
    "alt": "Completed landscape design with topiary boxwoods and palms at Central Florida estate home — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 357162
  },
  {
    "src": "/photos/lawn-landscape-card-1.jpg",
    "alt": "Backyard landscape design with mature bamboo privacy hedge, palms, manicured lawn, and travertine walkway — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "portfolio-card",
    "width": 1200,
    "height": 900,
    "bytes": 593150
  },
  {
    "src": "/photos/landscape-ryan-3.jpg",
    "alt": "White Mediterranean estate with palms and fresh sod in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 359347
  },
  {
    "src": "/photos/landscape-ryan-4.jpg",
    "alt": "Stucco home with palms and clean lawn around walkway in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 568024
  },
  {
    "src": "/photos/landscape-ryan-5.jpg",
    "alt": "Tall manicured hedge wall framing a turf strip in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 720,
    "bytes": 449142
  },
  {
    "src": "/photos/landscape-ryan-6.jpg",
    "alt": "Stucco home corner with mature oak and tidy hedge bed in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 720,
    "bytes": 522406
  },
  {
    "src": "/photos/landscape-ryan-7.jpg",
    "alt": "Privacy hedge with bougainvillea bloom and iron fence in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 720,
    "bytes": 487787
  },
  {
    "src": "/photos/landscape-ryan-8.jpg",
    "alt": "Modern white home with topiary boxwoods and palm cluster in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 484417
  },
  {
    "src": "/photos/landscape-ryan-9.jpg",
    "alt": "Tall manicured hedge alongside stucco home wing in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 567760
  },
  {
    "src": "/photos/landscape-ryan-10.jpg",
    "alt": "Pergola covered in bougainvillea over hardscape patio in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 960,
    "height": 1280,
    "bytes": 603407
  },
  {
    "src": "/photos/landscape-ryan-11.jpg",
    "alt": "Backyard with stone retaining wall and fresh mulched plant bed in Central Florida — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "secondary",
    "width": 960,
    "height": 1280,
    "bytes": 789462
  },
  {
    "src": "/photos/lawn-ryan-1.jpg",
    "alt": "Fresh mowing stripes under mature oak canopy in Central Florida — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 675616
  },
  {
    "src": "/photos/lawn-ryan-2.jpg",
    "alt": "Manicured walkway with hedge and ground cover edging in Central Florida — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 720,
    "height": 1280,
    "bytes": 495397
  },
  {
    "src": "/photos/lawn-ryan-3.jpg",
    "alt": "Brick paver walkway between Mediterranean homes with manicured hedges in Central Florida — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 720,
    "height": 1280,
    "bytes": 390398
  },
  {
    "src": "/photos/hardscape-ryan-1.jpg",
    "alt": "Wide paver patio with topiary boxwoods and umbrella in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "service-hero",
    "width": 1600,
    "height": 900,
    "bytes": 534219
  },
  {
    "src": "/photos/hardscape-ryan-2.jpg",
    "alt": "Stucco home with paver driveway and palm screen in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1280,
    "height": 720,
    "bytes": 382119
  },
  {
    "src": "/photos/hardscape-ryan-3.jpg",
    "alt": "Wide paver driveway alongside podocarpus hedge in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1280,
    "height": 960,
    "bytes": 523387
  },
  {
    "src": "/photos/hardscape-ryan-4.jpg",
    "alt": "Wide finished paver driveway leading to estate home in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1280,
    "height": 958,
    "bytes": 377928
  },
  {
    "src": "/photos/hardscape-ryan-5.jpg",
    "alt": "Stacked-stone retaining wall around pool-side plant bed in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1280,
    "height": 954,
    "bytes": 430450
  },
  {
    "src": "/photos/hardscape-ryan-6.jpg",
    "alt": "Curved retaining wall with round stone-bench planter steps in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1280,
    "height": 943,
    "bytes": 422353
  },
  {
    "src": "/photos/hardscape-ryan-7.jpg",
    "alt": "Stacked stone wall in beachside Central Florida setting — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1600,
    "height": 940,
    "bytes": 522027
  },
  {
    "src": "/photos/hardscape-ryan-8.jpg",
    "alt": "Newly installed paver walkway with polymeric sand-fill in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1194,
    "height": 1600,
    "bytes": 447137
  },
  {
    "src": "/photos/hardscape-ryan-9.jpg",
    "alt": "Brick-paver step-up at sliding patio door in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1196,
    "height": 1600,
    "bytes": 439369
  },
  {
    "src": "/photos/hardscape-ryan-10.jpg",
    "alt": "Travertine steps at dusk overlooking Central Florida landscape — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 882,
    "height": 1600,
    "bytes": 199447
  },
  {
    "src": "/photos/hardscape-ryan-11.jpg",
    "alt": "Gray herringbone paver patio at new construction home in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1204,
    "height": 1600,
    "bytes": 403082
  },
  {
    "src": "/photos/hardscape-ryan-12.jpg",
    "alt": "Crew installing paver walkway along side yard in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1191,
    "height": 1600,
    "bytes": 372599
  },
  {
    "src": "/photos/hardscape-ryan-13.jpg",
    "alt": "Brick paver side-yard walkway between stucco home and hedge in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1570,
    "height": 1600,
    "bytes": 426838
  },
  {
    "src": "/photos/hardscape-ryan-14.jpg",
    "alt": "Clean paver patio at back of new construction home in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1184,
    "height": 1600,
    "bytes": 415031
  },
  {
    "src": "/photos/concrete-ryan-1.jpg",
    "alt": "Finished concrete pads with white-gravel infill and RV driveway in Central Florida — Firsthand Lawn and Landscape",
    "category": "concrete",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "portfolio-card",
    "width": 1600,
    "height": 1189,
    "bytes": 465366
  },
  {
    "src": "/photos/concrete-ryan-2.jpg",
    "alt": "Diamond-pattern concrete driveway with gravel inlay at Central Florida home — Firsthand Lawn and Landscape",
    "category": "concrete",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1212,
    "height": 1600,
    "bytes": 338479
  },
  {
    "src": "/photos/concrete-ryan-3.jpg",
    "alt": "Freshly poured and finished concrete slab next to brick wall in Central Florida — Firsthand Lawn and Landscape",
    "category": "concrete",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1600,
    "height": 1185,
    "bytes": 328051
  },
  {
    "src": "/photos/concrete-ryan-4.jpg",
    "alt": "Fresh concrete pad at corner of fenced backyard in Central Florida — Firsthand Lawn and Landscape",
    "category": "concrete",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1600,
    "height": 1198,
    "bytes": 576036
  },
  {
    "src": "/photos/concrete-ryan-5.jpg",
    "alt": "Concrete pour in progress with crew at Central Florida residential site — Firsthand Lawn and Landscape",
    "category": "concrete",
    "area": "central-florida",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 459636
  },
  {
    "src": "/photos/ryan-daughter-1.jpg",
    "alt": "Ryan H., founder of Firsthand Lawn and Landscape, with his daughter in Firsthand-branded gear",
    "category": "ryan-portrait",
    "area": "n/a",
    "service": "n/a",
    "role": "about-hero",
    "width": 900,
    "height": 1200,
    "bytes": 161397
  },
  {
    "src": "/photos/ryan-daughter-2.jpg",
    "alt": "Ryan H., founder of Firsthand Lawn and Landscape, with his daughter",
    "category": "ryan-portrait",
    "area": "n/a",
    "service": "n/a",
    "role": "about-secondary",
    "width": 900,
    "height": 1200,
    "bytes": 248237
  },
  {
    "src": "/photos/ryan-portrait.jpg",
    "alt": "Ryan, owner of Firsthand Lawn and Landscape",
    "category": "ryan-portrait",
    "area": "n/a",
    "service": "n/a",
    "role": "secondary",
    "width": 591,
    "height": 1280,
    "bytes": 68555
  },

  // ── Auto-pulled CompanyCam batch (May 2026) ──────────────────────────
  {
    "src": "/photos/hero-1.jpg",
    "alt": "Backyard landscape design with manicured lawn, palms, and screened pool — Firsthand Lawn and Landscape",
    "category": "hero",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "hero",
    "width": 1600,
    "height": 1200,
    "bytes": 401336
  },
  {
    "src": "/photos/hardscape-1.jpg",
    "alt": "Travertine pool deck with raised spa and waterfall feature in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "service-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 287883
  },
  {
    "src": "/photos/hardscape-2.jpg",
    "alt": "Paver driveway installation in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 366935
  },
  {
    "src": "/photos/hardscape-3.jpg",
    "alt": "Paver patio adjacent to screened pool enclosure in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "windermere",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 427773
  },
  {
    "src": "/photos/hardscape-4.jpg",
    "alt": "Brick paver driveway in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "bay-hill",
    "service": "hardscape-installation",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 295159
  },
  {
    "src": "/photos/hardscape-5.jpg",
    "alt": "Two-story Mediterranean home with paver driveway and lawn in Central Florida — Firsthand Lawn and Landscape",
    "category": "hardscape",
    "area": "orlando",
    "service": "hardscape-installation",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 285920
  },
  {
    "src": "/photos/sod-1.jpg",
    "alt": "Fresh St. Augustine sod installation on a Central Florida front lawn — Firsthand Lawn and Landscape",
    "category": "sod",
    "area": "orlando",
    "service": "sod-installation",
    "role": "secondary",
    "width": 1024,
    "height": 768,
    "bytes": 178796
  },
  {
    "src": "/photos/orlando-area-hero.jpg",
    "alt": "Professionally maintained landscaping in Orlando, FL",
    "category": "sod",
    "area": "orlando",
    "service": "sod-installation",
    "role": "area-hero",
    "width": 1920,
    "height": 1080,
    "bytes": 709933
  },
  {
    "src": "/photos/lawn-1.jpg",
    "alt": "Maintained lawn with mowing stripes under mature oak canopy in Central Florida — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "service-hero",
    "width": 1600,
    "height": 1200,
    "bytes": 419293
  },
  {
    "src": "/photos/lawn-2.jpg",
    "alt": "Weekly lawn maintenance on a Central Florida residential property — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 440788
  },
  {
    "src": "/photos/lawn-3.jpg",
    "alt": "Mowed lawn alongside hedge and pool enclosure in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "windermere",
    "service": "lawn-maintenance",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 436315
  },
  {
    "src": "/photos/lawn-4.jpg",
    "alt": "Side-yard lawn alongside hedge in Bay Hill, FL — Firsthand Lawn and Landscape",
    "category": "lawn",
    "area": "bay-hill",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 366884
  },
  {
    "src": "/photos/landscape-1.jpg",
    "alt": "Landscape design with mixed beds alongside a luxury home in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 462064
  },
  {
    "src": "/photos/landscape-2.jpg",
    "alt": "Completed landscape design and installation in Central Florida — lush backyard with palm and hedge screening by Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "orlando",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 389296
  },
  {
    "src": "/photos/landscape-3.jpg",
    "alt": "Tall Podocarpus hedge along a Bay Hill property line — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "bay-hill",
    "service": "landscape-design",
    "role": "secondary",
    "width": 1600,
    "height": 1200,
    "bytes": 387295
  },
  {
    "src": "/photos/landscape-4.jpg",
    "alt": "Mixed planting bed with palms and ground covers in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 240,
    "height": 320,
    "bytes": 17230
  },
  {
    "src": "/photos/stump-1.jpg",
    "alt": "Palm cluster base in Bay Hill, FL — typical stump-grinding candidate. Firsthand Lawn and Landscape",
    "category": "stump",
    "area": "bay-hill",
    "service": "stump-grinding-removal",
    "role": "secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 384178
  },
  {
    "src": "/photos/bamboo-1.jpg",
    "alt": "Before-and-after of bamboo removal and yard transformation by Firsthand Lawn and Landscape",
    "category": "bamboo",
    "area": "bay-hill",
    "service": "bamboo-trimming-removal",
    "role": "secondary",
    "width": 1440,
    "height": 1440,
    "bytes": 383532
  },
  {
    "src": "/photos/winter-park-area-hero.jpg",
    "alt": "Professionally maintained landscaping in Winter Park, FL",
    "category": "winter-park",
    "area": "winter-park",
    "service": "lawn-maintenance",
    "role": "area-hero",
    "width": 1440,
    "height": 1920,
    "bytes": 807159
  },
  {
    "src": "/photos/winter-park-2.jpg",
    "alt": "Modern white-stucco home with palms in Winter Park, FL — Firsthand Lawn and Landscape",
    "category": "winter-park",
    "area": "winter-park",
    "service": "landscape-design",
    "role": "area-secondary",
    "width": 180,
    "height": 240,
    "bytes": 12131
  },
  {
    "src": "/photos/windermere-area-hero.jpg",
    "alt": "Professionally maintained landscaping in Windermere, FL",
    "category": "windermere",
    "area": "windermere",
    "service": "hardscape-installation",
    "role": "area-hero",
    "width": 1920,
    "height": 1080,
    "bytes": 573640
  },
  {
    "src": "/photos/windermere-2.jpg",
    "alt": "Single-story estate home and landscape in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "windermere",
    "area": "windermere",
    "service": "landscape-design",
    "role": "area-secondary",
    "width": 1200,
    "height": 1600,
    "bytes": 314615
  },
  {
    "src": "/photos/bay-hill-area-hero.jpg",
    "alt": "Professionally maintained landscaping in Bay Hill, FL",
    "category": "bay-hill",
    "area": "bay-hill",
    "service": "lawn-maintenance",
    "role": "area-hero",
    "width": 1920,
    "height": 1440,
    "bytes": 586736
  },
  {
    "src": "/photos/commercial-1.jpg",
    "alt": "Commercial property landscape maintenance in Central Florida — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "central-florida",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1200,
    "height": 1600,
    "bytes": 441253
  },
  {
    "src": "/photos/commercial-2.jpg",
    "alt": "Commercial office landscape with paver entrance in Central Florida — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 280456
  },
  {
    "src": "/photos/portfolio-1.jpg",
    "alt": "Mediterranean home with palm-lined drive in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "orlando",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 361396
  },
  {
    "src": "/photos/portfolio-2.jpg",
    "alt": "Backyard with paver patio and fresh sod in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "orlando",
    "service": "hardscape-installation",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 394749
  },
  {
    "src": "/photos/portfolio-3.jpg",
    "alt": "Tile-roof home with mature hedge bed in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 354103
  },
  {
    "src": "/photos/portfolio-4.jpg",
    "alt": "Wraparound porch with magnolia and trimmed hedges in Central Florida — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 439226
  },
  {
    "src": "/photos/portfolio-5.jpg",
    "alt": "Single-story Florida home with metal roof and large front lawn in Windermere, FL — Firsthand Lawn and Landscape",
    "category": "portfolio",
    "area": "windermere",
    "service": "lawn-maintenance",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 237797
  },
  {
    "src": "/photos/commercial-3.jpg",
    "alt": "Commercial dental practice frontage with new gravel bed and landscaping in Orlando, FL — Firsthand Lawn and Landscape",
    "category": "commercial",
    "area": "orlando",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1200,
    "height": 1600,
    "bytes": 455986
  },
  {
    "src": "/photos/landscape-5.jpg",
    "alt": "Fresh mulch and plant install along a Central Florida residential side yard — Firsthand Lawn and Landscape",
    "category": "landscape",
    "area": "central-florida",
    "service": "landscape-design",
    "role": "portfolio",
    "width": 1600,
    "height": 1200,
    "bytes": 364872
  }
];

export function photosByService(slug: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.service === slug);
}

export function photosByArea(slug: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.area === slug);
}

export function photosByRole(role: string): SitePhoto[] {
  return PHOTOS.filter((p) => p.role === role);
}

export function findPhoto(predicate: (p: SitePhoto) => boolean): SitePhoto | undefined {
  return PHOTOS.find(predicate);
}

/**
 * Pick a photo matching BOTH role + category. Falls back to category-only,
 * then role-only. Prior version ignored category on the role-match path, so
 * a call like pickHero("area-hero", "winter-park") returned whatever role
 * "area-hero" appeared first in the manifest regardless of locale.
 */
export function pickHero(role: string, category: string): SitePhoto | undefined {
  return (
    PHOTOS.find((p) => p.role === role && p.category === category) ??
    PHOTOS.find((p) => p.category === category) ??
    PHOTOS.find((p) => p.role === role)
  );
}
